### PR TITLE
Update manage.js.php

### PR DESCRIPTION
**Pull request by OutbackMatt**
fixes minor display issue with grid

### CODE REVIEW

**Comment by apmuthu** [comment]
Does this affect only mobile devices and does it spoil desktop viewing?

**Comment by OutbackMatt** [comment]
It affected normal desktop view. 
VERY minor adjustment

**Comment by apmuthu** [comment]
By stating that the desktop view has been affected - has it worsened it?

**Comment by OutbackMatt** [comment]
My 'fix' changed the view (specifically the desktop view but should also be mobile devices view - are they separate? I can't see separate mobile devices views).

The 'fix' removes the very narrow section of white space on the right hand side of the invoices >> Manage grid, that was caused by a calculation error originally.

**Comment by apmuthu** [comment]
@justinkelly: Is this narrow strip used for some special indications or is it a remnant of some now no longer listed field?

**Pull request closed without merging**
