### PR TITLE
Composer

### PR DESCRIPTION
**Pull request by JPG-Consulting**
Added composer (composer.json) for dependencies.

ZendFramework, HtmlPurifier and Smarty are now installed through composer. This allows easier maintenance of external libraries. Once the project is cloned or downloaded simply run: `composer install` to install the dependendencies. If any changes are made to the libraries inside `composer.json` simply run `composer update` to perform the update.

This update should allow for easier updates.

Composer is available at: [https://getcomposer.org/](https://getcomposer.org/)

### CODE REVIEW

**Comment by apmuthu** [comment]
The base branch does not use composer.

**Comment by JPG-Consulting** [comment]
Well that's why I suggested placing composer as it allows for further updates like going PSR-4 which right now is almost imposible as there are no autoloaders in place... Further more, some of the components such as Zend Framework 1, Smarty and HTMLPurifier are now supported in composer.

**Comment by apmuthu** [comment]
To keep it simple, the base branch does not use composer. End users can easily incorporate composer if they intend to upgrade and maintain their versions. SimpleInvoices is focussed in it's core and has patched libraries over time and upgrading libraries may render it problematic in some or all areas.

In fact we must de-Composer-ize projects to keep it easily understandable for newbies and developers of all hues. In quite a few instances only some versions of libraries will work and the presence of a composer.json file will be useful for downloading the same or at the very least include the appropriate version's download link in the install notes. It then does not impose on the end-user to use composer at all.

[De-Composer-ization is the PdfParser](https://github.com/smalot/pdfparser/issues/117) is a example.

**Comment by JPG-Consulting** [comment]
That's not a composer problem.

In composer you may specify which libraries shall be handled by composer and which libraries shouldn't. So you can keep modified/patched libraries outside of the composer file. In fact you can even use composer to include a library inside the vendor dir without being a requirement and, therefore it won't get updated. You may also specify a specific version of the library you are going to use. For example if I wish to stick strictlly with Smarty 2.6.28 you may do so... If you want to stick with 2.6.* you can also do it. So I don't really see a problem with it. For example:

```
{
    "name": "simpleinvoices/simpleinvoices",
    "description": "Making invoicing rock since '05",
    "type": "project",
    "license": "GPL-3.0",
    "require": {
        "php": "^5.3"
    },
    "autoload": {
        "psr-0": {
            "Zend_": "library/Zend"
        },
        "classmap": [
            "library/smarty/Smarty.class.php",
            "library/smarty/Smarty_Compiler.class.php",
            "library/smarty/Config_File.class.php"
        ]
    }
}
```

Would simply autoload the Zend Framework 1 and Smarty contained in the project without any updates at all. The only requirement in that composer file would be PHP 5.3 which would tell the developper which PHP version it is aimed at.

Some libraries are kept untouched and therefore it could go into the requirements section (For example ZF1) and, if you feel more confident, you may stick to a given version of it instead of allowing updates by default.

Composer really makes things easier... Except for the end user, but in that case you may include a zipped file with all the libraries. However its not that hard to run `composer install`.

What you are talking about is a missuse of composer and that can be tracked during the pull requests the same way as you can track erroneous code.

**Comment by apmuthu** [comment]
It is not composer being a problem at all. It is simple for regular ````include````s to be understandable for newbies and average programmers and to be able to use SI without much support.

**Comment by JPG-Consulting** [comment]
But is this an invoicing application or a PHP learning tutorial?

Nowadays autoloaders are widelly used. Keeping includes all around is like using buying an "analog" camera. It may be nice to lear about photography but you'll find problems all around as you wont be able to print your photos unless you have your own lab, and the film and chemicals needed will be hard to find now-a-days.

I've had problems loading Simple Invoices on a server running PHP 5.6 which is the oldestavailable binary for Windows. IMHO it SHOULD be updated. It's like developping an invoicing application in Cobol which wont run in PC newer than Windows 98. Windows 98 in 2016?

**Comment by apmuthu** [comment]
This instance of SimpleInvoices is being retained in "Legacy" mode to serve the thousands of users since it's very inception and to help ordinary non professional users to understand and code what they want to suit their needs.

Just because the latest and greatest versions of all libraries are touted about does not mean they are good for all. The bulk of the users need to understand / develop the code they will use if and when they want. A large number of understanding eyeballs will keep the codebase healthy and sustainable.

Professional entities / programmers are free to fork it and take it any way they will but hijacking the main project to take it out of reach of understanding of the average Joe is not envisaged.

Any new module (as third party plugins) being developed can have namespaces - there is no guarantee that someone else will not use the very same namespace and confuse everything!

Many companies are hiring top notch programmers to join Open Source projects and then scuttle them by making sure very few understand it.

All old versions of PHP / MySQL / Apache / XAMPP, etc are available and so are archived versions of Debian / CentOS, etc. Newer versions of PHP / MySQL have non-strict and compatible modes to run old code and established code changes are available to patch legacy code to run on newer PHP / MySQL versions. The older versions of PHP / MySQL are still supported since they can enjoy true Open Source licensing now that Oracle owns the lot and they can and will hold society (market) to ransom someday.

**Comment by JPG-Consulting** [comment]
Ok, understood so this is a dead project used for learning purposes but not as an invoicing tool. 

I remember the days when the community talked on getting it working on smartphones and now not even porting to a responsive layout.

I don't know how it works on your country but here almost everyone uses a mobile phone (Not easy to work with) or Windows Desktop. Non profesional users don't use Debian, Centos, Ubuntu, o whatever flavor of Linux... nor will they use OpenBSD although some of them use the core on their Macs. But not having a binary is a tremendous downside to them. Further more, as you probably know the binary version should be compiled with the same VC version or Apache and PHP don't go together well... so setting up an enviroment can be harsh when there is no support for it and i think PHP 5.6 is the last supported version but incompatible with Simple Invoices.  Therefore it is just becoming a big dinosaur from the past which will die... And i say it sadly as I placed some time and effort trying to keep it updated since it was hosted on Google Code. How canpeople install an old System just to devolp for Simple Invoices? How are you willing to keep invoices secure with an unsecure underalying environment? and further more, i know of several Hosting providers that are removing PHP 5.3 support... So right now some hosts will only allow 5.4 and, when that is over, it is over for Simple Invoices. Really sad to hear that when the few people at Google Plus talk about making the way toward newer versions of PHP and people are complaining about dowgradin PHP. Sad.

**Comment by apmuthu** [comment]
This is very much a live project but in a skeletally basic form to enable end users to adapt it to their needs. Some developers have actually used bootstrap to make it play nice with mobile devices - check out their forks.

Effort is now being made to make SI agnostic of PHP versions.

PHPDesktop is one of the projects used to make binaries of PHP applications like SI usable on the desktop - Linux/Windows/Mac.

The project whilst eminently suitable for learning, understanding and easy and simple local installs is actually being used across the world by small and medium businesses for quite some time.

Please list the places where in PHP 5.6 the code fails and we can refactor the code to address the versions issue. Later versions of PHP / MySQL do not look kindly on dates being '0000-00-00' where the non strict option is advisable for now.

**Pull request closed without merging**
